### ISSUE TITLE
Awesome module!!!

### ISSUE THREAD

**Issue by lfreyholtz** [der-lukas/framer-Symbols#10]
But one question - do you have any thoughts on changing text size between states?  Seems it doesn't work.  I've also tried reaching into the children on change:frame to modulate from the start to the end size, which sorta works but the cycling of states resets the font size - seemingly to the size it was during the last state...

Any thoughts?

**Comment by der-lukas** [comment]
Hey! I just tried it by changing this demo-project and it worked as expected: https://framer.cloud/aCgol
Could you share the project where it doesn't work?

**Comment by lfreyholtz** [comment]
Hey  - yup, take a look here:
https://framer.cloud/EvPIb

A couple things that seem to be clashing somehow:

1. using templates in text view + auto height - works in the first state, but loses it after first state transition (I see this with Framer's states too)
2. seems the constraints aren't holding either - I could solve this with padding, but seems like a hack...

What do you think?

**Comment by der-lukas** [comment]
I just pushed a minor update for the module, that fixes the contraints for textlayers! 
What's not possible is to have different fontsizes/styles inside one textLayer - so breaking those apart into seperate textlayers fixes the fontsize transitions!

Here your updated example:
https://framer.cloud/fTPKV
