### ISSUE TITLE
Unassigned target items in a symbol throw a vague error

### ISSUE THREAD

**Issue by Taitrnator** [der-lukas/framer-Symbols#13]
First of all, l <3 this project and it's the one thing that makes framer a better option than HTML prototyping for me, so thanks for maintaining this. 

So I discovered this trying to create a list of symbols populated with JSON:
<img width="412" alt="screen shot 2018-07-13 at 4 17 58 pm" src="https://user-images.githubusercontent.com/6832528/42717822-b3f011c6-86b8-11e8-9052-8e07d6a52cdb.png">

notice, the second element is not getting values. The bug does seem to be based on trying to reuse an ID: 

`Error: Can not set html: There's already an element with id 'id_QrcNibT3d' in this document'`
<img width="601" alt="screen shot 2018-07-13 at 4 17 51 pm" src="https://user-images.githubusercontent.com/6832528/42717823-b417fa2e-86b8-11e8-9a13-5ec41ac017e2.png">

Stack trace didn't really help identify root cause here. 

So after a lot of manual debugging, I realized **its caused by adding a target to an item you're using for a symbol, and not assigning a value to it when you instantiate the symbol.**

<img width="261" alt="screen shot 2018-07-13 at 4 17 38 pm" src="https://user-images.githubusercontent.com/6832528/42717825-b44dc302-86b8-11e8-9147-a8dd94b5c0a6.png">

For now, I just got rid of the target, but it's one I plan to use later. 

I can take a look at this on the weekend possibly and make a pull request if so, but wanted to point out the bug and the workaround.

**Comment by der-lukas** [comment]
Hey! Thanks for the kind words! 

You are right that this is happening because you targeted the shape inside the module!

But you never have to target a descendant of a symbol because you can access those simply like you would access the props:

symbolInstance.descendantName

So for example you can say: 

button.label.text = „Submit“
