### ISSUE TITLE
Unable to add Events to the Symbol before creating instances

### ISSUE THREAD

**Issue by absentees** [der-lukas/framer-Symbols#2]
Im currently developing a Header with a some links and a profile image that will appear on multiple screens.

In the modules current state i will have to create several instances of the header and add the same events to all of the instances.

It would be great if you could do something like the following:

```
MainHeader = Symbol(Header)

MainHeader.ProfileImage.onTap ->
  flow.showNext(ProfilePage)

HomepageHeader = new MainHeader
    parent: Homepage

ProfilePageHeader = new MainHeader
    parent: ProfilePage
```

Each instance of MainHeader will have a Profile Image that will click through to the Profile Page.

What do you think?

**Comment by der-lukas** [comment]
Yeah, this would make sense... 
I'm gonna give this a try. Or do you maybe have some time to give this a go?

**Comment by der-lukas** [comment]
Hm I've done some investigation and just had following idea:

@steveruizok created an ActionLayer-module, which I could import as dependency and instead of extending Layer, I'm gonna extend ActionLayer to have the goven actions available! 

https://github.com/steveruizok/ActionLayer

**Comment by steveruizok** [comment]
Just as an update, ActionLayer is probably overkill for most use cases, however a lot of my more current classes use callbacks that are set from options.

The pattern is:

```coffeescript
class Header extends Layer
	constructor: (options = {}) ->
		@_action = options.action ? -> null

		super options
		
	@define "action",
		get: -> return @_action
		set: (func) ->
			@off Events.Tap, @_action
			@_action = func
			@on Events.Tap, @_action
```

A basic implementation:

```coffeescript
header = new Header
	action: -> print 'hello'
```

And that action can be changed and reset later using the `action` property.

```coffeescript
header = new Header
	action: -> print 'hello'
	
header.action = -> print 'goodbye'
```

For a more complicated implementation, check out my recent update to [framer-icon](https://github.com/steveruizok/framer-icon).

**Comment by der-lukas** [comment]
Thanks for your input @steveruizok! I'm going to look into it! By the way: I'd also really love your contribution to this module if you find some time and think this module can be of value! ;)

**Comment by der-lukas** [comment]
I've just updated the module to support commonEvents!

```coffeescript
commonActions = 
	'MouseOver': -> @.animate "hover"
	'MouseOut': -> @.animate "default"
	'TapStart': -> @.animate "active"
	'TapEnd': -> @.animate "hover"

PrimaryButton = Symbol(button_default, commonStates, commonActions)
```

It also works with descendants:

```coffeescript
commonActions = 
  'MouseOver': -> @.animate "hover"
  'MouseOut': -> @.animate "default"
  'TapStart': -> @.animate "active"
  'TapEnd': -> @.animate "hover"
  descendantName:
    'Tap': -> print "Foo"
```

Here's a demo-prototype showing a basic example with buttons: https://framer.cloud/FHRPZ

Let me know what you think!

**Comment by der-lukas** [comment]
@absentees does it work for you? I think I'm going to close this! ;)

**Comment by absentees** [comment]
@der-lukas this is great, i'll let you know how i go when i add my next symbol :)
