### ISSUE TITLE
Feedback & revised sample – take it or leave it :)

### ISSUE THREAD

**Issue by pxsmith** [der-lukas/framer-Symbols#3]
Hey @der-lukas, this is a really cool module. Thanks for making this and putting it out into the world! It’s really useful, and solves a problem I have with Framer. I did have a bit of a hard time understanding it, and getting it going though. I have attached a revised sample project with more thorough inline comments. This may help other get started faster. Take it or leave it. :)

[buttonSymbol-example-revised.framer.zip](https://github.com/der-lukas/framer-Symbols/files/1376551/buttonSymbol-example-revised.framer.zip)

And here’s a bit of feedback surrounding the readme. Consider deemphasizing the Framer Modules app, as it distracted me from actually using your module. Also, it is a bit difficult to find the example Framer file, which was key for me to actually figure out how to get it to work. It’d be nice to give that more attention, or potentially turn it into a button. I think the readme can be made more clear in generally, but those are two specific ways to make it better, in my opinion.

Again, thanks for making this! 👏

**Comment by der-lukas** [comment]
Hey @pxsmith!

Thanks for the feedback and the revised example! The readme would definitely need some improvements and I can imagine that the module's concept/usage is a little hard to grasp with the descriptions and examples given.

I'd love to give this module some more attention, but currently can't find the time to really focus on improvements.

If it's not to much to ask and you maybe have a some time on your hand, it would be awesome if you could create a pull-request with improvements for the readme!

Also if you have ideas for improvements, features or own usage-examples to share, please get back to me!

**Comment by pxsmith** [comment]
@der-lukas I’ll open a PR when I have a free moment, no problem.
