### ISSUE TITLE
Error: SVGGroup and SVGPath do not support the `copy` method

### ISSUE THREAD

**Issue by bruskowski** [der-lukas/framer-Symbols#4]
When placing shapes (= everything that's not a frame, image, icon or text) in a template in Design mode, Framer V111 throws the following error message when trying to create a Symbol from this template.

Error: SVGGroup and SVGPath do not support the `copy` method

According to the Framer team, a possible workaround would be to wrap the shapes in a frame and copy only that frame, not the individual targeted SVGPaths and SVGGroups. 

So I guess framer-Symbols would need to skip SVGPaths and SVGGroups when iterating through all children of a template and copy the parent 'frame' only to avoid this error and to allow shapes drawn in Framer Design mode to be placed within templates.

My workaround right now is using imported SVGs only which show in Design mode as "Icon" (or image, I guess) and are apparently treated differently.

Loves this module, makes my prototypes' design more easily adjustable and the code shorter and more readable. Allowing me to focus on the essential interactions more. Thanks!

**Comment by der-lukas** [comment]
Thanks for the report! Could you supply a demo project for this? Did you try reproducing this in Framer Beta? I believe I heard that they are going to support the `copy` method in a future release, so this might fix itself, but I'll ask Framer about this and will investigate further! :)

**Comment by bruskowski** [comment]
Sure, here is a demo: https://framer.cloud/THxFt/
The demo includes a modified version of your module with my unsuccessful attempt at circumventing the issue. (Symbol-test.coffee)
Did try it in Framer Beta beta/8d15287a5 now, with the same results. The answer of the Framer team included the words "not yet", though, so you probably have heard right.
Thanks!

**Comment by der-lukas** [comment]
Hey! I just pushed a fix for this issue! 
Here's your updated prototype: https://framer.cloud/HZiiB/

I'll close the issue for now - feel free to reopen it if you run into other problems - I'm not sure if my solution is "rock solid"! 🤓

**Comment by bruskowski** [comment]
I ran into an error when using the updated module with my current project. Did not have time to explore further and thus downgraded again. I'll give it another as soon as I find some time!

**Comment by der-lukas** [comment]
Thanks for reporting this! Fixed it now!
