### ISSUE TITLE
Request: Access/Manipulate child elements within Symbol Object (like Design Components module)

### ISSUE THREAD

**Issue by aalokt89** [der-lukas/framer-Symbols#5]
I love how the Design-Components module allows you to access child layers and properties within that symbol object: https://cl.ly/1I2Z1v301V45

It'd be great if you implemented this too, Instead of having to use dot notation (button.text.text = "blah"), which can become really time consuming and tedious if you have a lot of child components in your symbol.

Thanks!

**Comment by der-lukas** [comment]
Done! ;)
