### ISSUE TITLE
Request: Ability to add properties to common states object

### ISSUE THREAD

**Issue by aalokt89** [der-lukas/framer-Symbols#6]
Right now (from what I understand), you can only add a 'template' and 'animationOptions' to the common states object. Since you can't detect x/y and other certain values from the design-state-template, It would be great if you could add those properties within the object instead of having to add them separately https://cl.ly/1T0A3X0S1r1E

**Comment by der-lukas** [comment]
Hey! Just pushed an update with the ability to add x/y as props for commonStates!

```#Card states
cardStates =
    animationOptions:
        curve: Spring(damping: .7)
        time: .4
    open:
        template: cardOpen
        x: 0
        y: 0
```

Here’s your updated example: https://framer.cloud/hfojz
