### ISSUE TITLE
Animation:Options on CommonStates don't appear to be recognized.

### ISSUE THREAD

**Issue by gnyrd** [der-lukas/framer-Symbols#7]
In this example, I set the time to 15, it's obviously not working.

https://framer.cloud/GrBnp

**Comment by der-lukas** [comment]
Hey! Thanks for reporting this! 

I just investigated this and found out that this only happens for SVGLayers inside Symbols - so it works for Frames! 

I already found where the problem is and I'll try to fix it! 👍

**Comment by der-lukas** [comment]
Alright - got it fixed and pushed an update! ✅

Here's your updated example: https://framer.cloud/BmcvW

**Comment by gnyrd** [comment]
Very cool! 

thanks!!


I’m still very new to Framer.. is there any kind of module dependency version control mechanism? IOW, how would I easily update projects using your module?

**Comment by der-lukas** [comment]
Sadly there's no real version control for modules... But it seems that you installed the module via "Framer Modules"-App. The easiest way of updating would be to delete the module through this app and just reinstalling it after that, which will download the latest version from GitHub!

**Comment by gnyrd** [comment]
Again, thanks!

Maybe I’ll talk to the Framer Modules author about a versioning based notification & updating mechanism...
